### ISSUE TITLE
Error on zpl element "4030401100+67000000": EC128-6: Only numeric values can be encoded with C128-C (Invalid char at position 11)

### ISSUE THREAD

**Issue by bjt19882222** [BinaryKits/BinaryKits.Zpl#151] opened 2022-12-16 06:51 UTC
Hi,

i have an valid zpl file which can be converted here:
http://labelary.com/viewer.html

But on your site and with your script i get this error:
https://binarykits-zpl-viewer.azurewebsites.net/
Error on zpl element "4030401100+67000000": EC128-6: Only numeric values can be encoded with C128-C (Invalid char at position 11).

Why?
Can you help please?

**Comment by primo-ppcg** [comment] 2023-01-09 05:35
The only way I can recreate this error is by explicitly forcing Type C on non-numeric data:

```zpl
^XA
^FO10,10^BY2^BCN,40^FD>;4030401100+67000000^FS
^XZ
```
However, this produces a slightly different message. If you could provide the relevant `^BC` command, it would help to determine if/what the issue is.

**Comment by samilalgul** [comment] 2023-04-12 12:49
Type C data could not includes char or special chars?

**Comment by sibit** [comment] 2023-06-30 11:02
I have the same issue, I just detected right now. Did you get the solution? 

thanks!

**Comment by primo-ppcg** [comment] 2023-06-30 11:11
> I have the same issue, I just detected right now. Did you get the solution?

Excellent. Could you provide the ZPL that produces the error?

**Comment by sibit** [comment] 2023-06-30 11:26
Hi! this is the sentence ZPL that I'm using into this software.
When I remove this part >890>6C1 is working properly (that part contains C1 into the barcode).
How I can add C1 or other text (Batch number sometimes contains text 'ABC123) into the Code128 or GS1-128?

Thanks a lot!

                        string pzpl = @"^XA^FO197,495^BY5^BCN,150,N,N^FD>;>89181752625>8103181450701>890>6C1^FS^FT239,691^CI0^A0N,50,68^FD(91) 81752625 (10) 3181450701 (90) C1^FS^PQ1,0,1,Y^XZ";

**Comment by primo-ppcg** [comment] 2023-06-30 12:42
Not all escapes are supported in hand-rolled GS1, the relevant code is here:
https://github.com/BinaryKits/BinaryKits.Zpl/blob/92bf320db189d96be40d55c489db2a2f4c7368d8/src/BinaryKits.Zpl.Viewer/ElementDrawers/Barcode128ElementDrawer.cs#L62-L65
I'm currently working on a new Barcode rendering (#171), I'll add support for more escapes to GS1.

**Comment by sibit** [comment] 2023-07-03 14:07
Thanks primo-ppcg. 
I really don't undestand why is not working with all scapes. This scape 90 or 91 is normal, or not?

**Comment by primo-ppcg** [comment] 2023-07-03 15:50
The part that can't be parsed is `>6C1`, which switches to codeset B for the final two character.

**Comment by sibit** [comment] 2023-07-03 16:50
thanks for your answer. That is something that I can solve into the zpl barcode code, or is this issue into the c# project?

anyway, why I cannot add a breakpoint into Encode function?
using var image = barcodeElement.Encode(barcodeType, content);

I'm trying to help with this issue but I cannot access and check it! :(

**Comment by primo-ppcg** [comment] 2023-07-04 05:09
The `Encode` method belongs to an external library. This error (and several others) will be resolved in the next release.

**Comment by sibit** [comment] 2023-09-14 14:25
Hey dude! 
how is going with your development?! :P

**Comment by primo-ppcg** [comment] 2023-09-15 05:59
I was holding out for the next release of [ZXing.Net](https://github.com/micjahn/ZXing.Net), although I suppose that might not be any time soon. If I wanted to accelerate the release, I could possibly makes PRs for all of the [upstream commits](https://github.com/zxing/zxing/commits/master).

**Closed** 2024-04-26 03:04 UTC
Labels: enhancement
